### ISSUE TITLE
Error: failed to get random outputs to mix: failed to get random outs

### ISSUE THREAD

**Issue by limosek** [letheanVPN/blockchain#113]
If there is lot of transactions in wallet (like generated by mining) and we want to send more coins, it ends with 
Error: failed to get random outputs to mix: failed to get random outs
Would be nice if wallet uses some strategy to split payment and send it as more transactions than just produce error.

**Comment by pallas1** [comment]
This is evident now that there are few transactions in the network. It should be less of a problem in the future, but anyway as you said it should take care of it automatically somehow. Even though that would raise fees which are already pretty high.

**Comment by valiant1x** [comment]
An alternative to splitting payments is using the `sweep_unmixable` command first, which sweeps all of your unmixable outputs in an identifiable transaction to yourself. After that succeeds and creates enough outs, you can then transfer normally.

We should work on adding a feature to auto-split using available outs.
