### ISSUE TITLE
BUG: user folder

### ISSUE THREAD

**Issue by Snider** [letheanVPN/blockchain#218]
We are getting a .Lethean folder created. @ganz3891 you free to adjust this?

**Comment by ganz3891** [comment]
Hi @Snider,
Ah yes i will adjust this

**Comment by Snider** [comment]
Too late :P found the issue Commit coming; came to get the issue number :)

**Comment by ganz3891** [comment]
ah nice, really sorry for the late response

**Comment by Snider** [comment]
> ah nice, really sorry for the late response

No sorry required for OS buddy :)
