### ISSUE TITLE
Unable to compile shared library: -DBUILD_SHARED_LIBS=1

### ISSUE THREAD

**Issue by Pinusno** [letheanVPN/blockchain#80]
I am using Ubuntu 16.04 x86_64 - master branch
GCC -v 5.4.0

This issue is related to the changes of #59. before I was able to compile with  
 -DBUILD_SHARED_LIBS=1 but I had unfortunately linking errors:

command: cmake -DBUILD_SHARED_LIBS=1 .

CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
  "ringct" of type SHARED_LIBRARY
    depends on "cryptonote_basic" (weak)
    depends on "cryptonote_core" (weak)
    depends on "blockchain_db" (weak)
  "cryptonote_basic" of type SHARED_LIBRARY
    depends on "cryptonote_core" (weak)
    depends on "blockchain_db" (weak)
    depends on "ringct" (weak)
  "cryptonote_core" of type SHARED_LIBRARY
    depends on "blockchain_db" (weak)
    depends on "ringct" (weak)
    depends on "cryptonote_basic" (weak)
  "blockchain_db" of type SHARED_LIBRARY
    depends on "ringct" (weak)
    depends on "cryptonote_basic" (weak)
    depends on "cryptonote_core" (weak)
At least one of these targets is not a STATIC_LIBRARY.  Cyclic dependencies are allowed only among static libraries.

before v2.0.0:
libcryptonote_basic.so: undefined reference to `cryptonote::construct_miner_tx(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, cryptonote::account_public_address const&, cryptonote::transaction&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned char)'
collect2: error: ld returned 1 exit status
CMakeFiles/build.dir/build.make:62: recipe for target 'build/bin' failed

Do you have any suggestions on how to create a usable intensecoin library?

**Comment by marcel1974** [comment]
I am having the the same problem on ubuntu 18.04.
How can I resolve the problem?
